---
- hosts: KubCluster
  become: True
  tasks:
  - name: Install Chef-inspec
    apt:
      deb: https://packages.chef.io/files/stable/inspec/4.20.2/ubuntu/18.04/inspec_4.20.2-1_amd64.deb
      
  - name: Execute static assessment
    command: inspec exec https://github.com/dev-sec/linux-baseline --reporter html:/tmp/inspec_report.html --chef-license=accept
    register: result
    failed_when:
      - result.rc == 1
  
  - fetch:
      src: /tmp/inspec_report.html
      dest: ../Results/
